#ifndef LIBDBPAUTOPATCHERPATCHFILE_GLOBAL_H
#define LIBDBPAUTOPATCHERPATCHFILE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBDBPAUTOPATCHERPATCHFILE_LIBRARY)
#  define LIBDBPAUTOPATCHERPATCHFILESHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBDBPAUTOPATCHERPATCHFILESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBDBPAUTOPATCHERPATCHFILE_GLOBAL_H
