{
  "sudo": "required",
  "services": [
    "docker"
  ],
  "before_install": [
    "git clone --recursive https://github.com/killergg789/DualBootPatcher -b killergg789-patch-1 DualBootPatcher/",
    "docker pull yshalsager/dualbootpatcher:9.3.0-4-base",
    "docker pull yshalsager/dualbootpatcher:9.3.0-4-android",
    "docker pull yshalsager/dualbootpatcher:9.3.0-4-linux"
  ],
  "script": [
    "mkdir $HOME/.android",
    "mkdir -p ${TRAVIS_BUILD_DIR}/DualBootPatcher/builder/ && cd ${TRAVIS_BUILD_DIR}/DualBootPatcher/",
    "docker run --rm -i -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v \"$(pwd):/builder/DualBootPatcher:rw,z\" -v \"${HOME}/.android:/builder/.android:rw,z\" yshalsager/dualbootpatcher:9.3.0-4-android bash << EOF\ncd DualBootPatcher/builder && cmake .. -DMBP_BUILD_TARGET=android -DMBP_BUILD_TYPE=debug && make -j16 && rm -rf assets && cpack && make apk -j16\nmake android-system_armeabi-v7a -j16 && make -C data/devices -j16\nexit\nEOF\n",
    "docker run --rm -i -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v \"$(pwd):/builder/DualBootPatcher:rw,z\" -v \"${HOME}/.android:/builder/.android:rw,z\" yshalsager/dualbootpatcher:9.3.0-4-linux bash << EOF\n# Build Utilities Zip\ncd ~/DualBootPatcher/builder && ./utilities/create.sh\n# Build Linux\ncmake .. -DMBP_BUILD_TARGET=desktop -DMBP_PORTABLE=ON && make -j16 && cpack\nexit\nEOF\n"
  ],
  "after_success": [
    "export TRAVIS_CURRENT_DATE=$(date +\"%d%m%y-%Hh%Mm\")",
    "ls -l ${TRAVIS_BUILD_DIR}/DualBootPatcher/Android_GUI/build/outputs/apk/debug/Android_GUI-debug.apk",
    "md5sum ${TRAVIS_BUILD_DIR}/DualBootPatcher/Android_GUI/build/outputs/apk/debug/Android_GUI-debug.apk",
    "ls -l ${TRAVIS_BUILD_DIR}/DualBootPatcher/builder/utilities/DualBootUtilities-9.3.0.zip",
    "md5sum ${TRAVIS_BUILD_DIR}/DualBootPatcher/builder/utilities/DualBootUtilities-9.3.0.zip",
    "ls -l ${TRAVIS_BUILD_DIR}/DualBootPatcher/builder/DualBootPatcher-9.3.0-Linux.zip",
    "md5sum ${TRAVIS_BUILD_DIR}/DualBootPatcher/builder/DualBootPatcher-9.3.0-Linux.zip",
    "cd ${TRAVIS_BUILD_DIR}/DualBootPatcher/Android_GUI/build/outputs/apk/debug/ &&  curl --upload-file ./Android_GUI-debug.apk https://transfer.sh/Android_GUI-debug-Killergg.apk",
    "cd ${TRAVIS_BUILD_DIR}//DualBootPatcher/builder/utilities/ && curl --upload-file ./DualBootUtilities-9.3.0.zip https://transfer.sh/DualBootUtilities-9.3.0-Killergg.zip",
    "cd ${TRAVIS_BUILD_DIR}/DualBootPatcher/builder/ && curl --upload-file ./DualBootPatcher-9.3.0-Linux.zip https://transfer.sh/DualBootPatcher-9.3.0-Linux.zip"
  ],
  "language": "ruby",
  "group": "deprecated-2017Q4",
  "dist": "trusty",
}
