#ifndef LIBDBPAUTOPATCHERSTANDARD_GLOBAL_H
#define LIBDBPAUTOPATCHERSTANDARD_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBDBPAUTOPATCHERSTANDARD_LIBRARY)
#  define LIBDBPAUTOPATCHERSTANDARDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBDBPAUTOPATCHERSTANDARDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBDBPAUTOPATCHERSTANDARD_GLOBAL_H
