#!/system/bin/sh
#Thermal control degC
#Change thermal control degC:
#Start 75degC Stop 72degC

echo "75" > /sys/devices/system/cpu/cpufreq/kthermal/temp_limit_degC_start
echo "72" > /sys/devices/system/cpu/cpufreq/kthermal/temp_limit_degC_stop
