#!/system/bin/sh
#Zram size and swappines
#Change zram disksize-swappines:
#Zram: Disable zram and swappines

sleep 5
#Disk 1
swapoff /dev/block/zram0
echo 1 > /sys/block/zram0/reset
#Disk 2
swapoff /dev/block/zram1
echo 1 > /sys/block/zram1/reset
#Disk 3
swapoff /dev/block/zram2
echo 1 > /sys/block/zram2/reset
#Disk 4
swapoff /dev/block/zram3
echo 1 > /sys/block/zram3/reset
