#!/system/bin/sh
#Fast charge
#Enable fast charge:
#On

echo "1" > /sys/kernel/fast_charge/force_fast_charge

# Display dialog window

if [ ! -f /system/etc/init.d/*dkfastcharge_002-on ]; then
	rm /sdcard/ausdim_twk_dlg_helper

	am start -a android.intent.action.MAIN -e message "If you enable fast charge access to phone storage via usb it will disabled." -e title "Fast charge warning" -e okstyle "Ok" -n dk.ausdim.tweaks.dialog.helper/.AusdimTweaksDialogActivity

	while [ ! -f /sdcard/ausdim_twk_dlg_helper ]
	do
		/sbin/busybox sleep 1
	done

	rm /sdcard/ausdim_twk_dlg_helper

fi
