#!/system/bin/sh
#Ext4 Tweaks
#Optimized mounting of /data and /cache:
#Off

sync
/sbin/busybox mount -o remount,commit=0,noatime $CACHE_DEVICE /cache

sync
/sbin/busybox mount -o remount,commit=0,noatime $DATA_DEVICE /data

sync
