#ifndef LIBDBPAUTOPATCHERJFLTE_GLOBAL_H
#define LIBDBPAUTOPATCHERJFLTE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBDBPAUTOPATCHERJFLTE_LIBRARY)
#  define LIBDBPAUTOPATCHERJFLTESHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBDBPAUTOPATCHERJFLTESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBDBPAUTOPATCHERJFLTE_GLOBAL_H
