#!/system/bin/sh
#CPU Undervolting
#Change CPU voltage:
#-75 mV

echo "1225 1200 1175 1150 1125 1100 1062 1012 975 950 925 900 887 862 835 825 825 800 800 800 775 775 775 " > /sys/devices/system/cpu/cpu0/cpufreq/UV_mV_table

# Display dialog window

if [ ! -f /system/etc/init.d/*dkcpuuv_003-75 ]; then

	rm /sdcard/ausdim_twk_dlg_helper

	am start -a android.intent.action.MAIN -e message "You are undervolting your CPU too much, so your device maybe isn't stable and maybe reboot." -e title "CPU Voltage warning" -e okstyle "Ok" -n dk.ausdim.tweaks.dialog.helper/.AusdimTweaksDialogActivity

	while [ ! -f /sdcard/ausdim_twk_dlg_helper ]
	do
		/sbin/busybox sleep 1
	done

	rm /sdcard/ausdim_twk_dlg_helper

fi
