#!/system/bin/sh
#Thermal control degC
#Change thermal control degC:
#Start 90degC Stop 87degC

echo "90" > /sys/devices/system/cpu/cpufreq/kthermal/temp_limit_degC_start
echo "87" > /sys/devices/system/cpu/cpufreq/kthermal/temp_limit_degC_stop
