#!/system/bin/sh
#Thermal control degC
#Change thermal control degC:
#Start 85degC Stop 82degC

echo "85" > /sys/devices/system/cpu/cpufreq/kthermal/temp_limit_degC_start
echo "82" > /sys/devices/system/cpu/cpufreq/kthermal/temp_limit_degC_stop
