#!/system/bin/sh
#Zram size and swappines
#Change zram disksize-swappines:
#Zram: 750mb Swappines: 85percent

SIZE="187"
sleep 5
#Disk 1
swapoff /dev/block/zram0
echo 1 > /sys/block/zram0/reset
echo $(( $SIZE * 1024 * 1024 )) > /sys/block/zram0/disksize
mkswap /dev/block/zram0
swapon /dev/block/zram0
echo 85 > /proc/sys/vm/swappiness
#Disk 2
swapoff /dev/block/zram1
echo 1 > /sys/block/zram1/reset
echo $(( $SIZE * 1024 * 1024 )) > /sys/block/zram1/disksize
mkswap /dev/block/zram1
swapon /dev/block/zram1
echo 85 > /proc/sys/vm/swappiness
#Disk 3
swapoff /dev/block/zram2
echo 1 > /sys/block/zram2/reset
echo $(( $SIZE * 1024 * 1024 )) > /sys/block/zram2/disksize
mkswap /dev/block/zram2
swapon /dev/block/zram2
echo 85 > /proc/sys/vm/swappiness
#Disk 4
swapoff /dev/block/zram3
echo 1 > /sys/block/zram3/reset
echo $(( $SIZE * 1024 * 1024 )) > /sys/block/zram3/disksize
mkswap /dev/block/zram3
swapon /dev/block/zram3
echo 85 > /proc/sys/vm/swappiness
