#!/system/bin/sh
#exFat support
#Control exFat drivers to support exFat formatted external SD cards:
#On (default)

insmod /lib/modules/exfat_core.ko
insmod /lib/modules/exfat_fs.ko

rm /sdcard/ausdim_twk_dlg_helper

am start -a android.intent.action.MAIN -e message "exFat is now enabled." -e title "Enable exFat" -e okstyle "Ok" -n dk.ausdim.tweaks.dialog.helper/.AusdimTweaksDialogActivity

while [ ! -f /sdcard/ausdim_twk_dlg_helper ]
do
	/sbin/busybox sleep 1
done

rm /sdcard/ausdim_twk_dlg_helper
