#!/system/bin/sh
#exFat support
#Control exFat drivers to support exFat formatted external SD cards:
#Off


# Check if script is called by ausdim-tweaks app and if so, display
# appropriate messages

if [ ! -f /system/etc/init.d/*dkexfat_005-off ]; then

	RESULT=`/sbin/busybox mount | grep exfat`

	if [ ! -z "$RESULT" ]; then

		rm /sdcard/ausdim_twk_dlg_helper

		am start -a android.intent.action.MAIN -e message "WARNING: You are using exFat currently. It will be disabled after next reboot and you will not be able to access your external SD card anymore!" -e title "Disable exFat" -e okstyle "Ok" -n dk.ausdim.tweaks.dialog.helper/.AusdimTweaksDialogActivity

		while [ ! -f /sdcard/ausdim_twk_dlg_helper ]
		do
			/sbin/busybox sleep 1
		done

		rm /sdcard/ausdim_twk_dlg_helper

	else
		rmmod /lib/modules/exfat_fs.ko
		rmmod /lib/modules/exfat_core.ko

		rm /sdcard/ausdim_twk_dlg_helper

		am start -a android.intent.action.MAIN -e message "exFat is now disabled. Please remember to enable again if you intend to use exFat formatted storage!" -e title "Disable exFat" -e okstyle "Ok" -n dk.ausdim.tweaks.dialog.helper/.AusdimTweaksDialogActivity

		while [ ! -f /sdcard/ausdim_twk_dlg_helper ]
		do
			/sbin/busybox sleep 1
		done

		rm /sdcard/ausdim_twk_dlg_helper

	fi

else

	rmmod /lib/modules/exfat_fs.ko
	rmmod /lib/modules/exfat_core.ko

fi
