// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_FILEWRITE_MBTOOL_DAEMON_V3_H_
#define FLATBUFFERS_GENERATED_FILEWRITE_MBTOOL_DAEMON_V3_H_

#include "flatbuffers/flatbuffers.h"


namespace mbtool {
namespace daemon {
namespace v3 {

struct FileWriteRequest;
struct FileWriteResponse;

struct FileWriteRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ID = 4,
    VT_DATA = 6
  };
  int32_t id() const { return GetField<int32_t>(VT_ID, 0); }
  const flatbuffers::Vector<uint8_t> *data() const { return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_DATA); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ID) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_DATA) &&
           verifier.Verify(data()) &&
           verifier.EndTable();
  }
};

struct FileWriteRequestBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(int32_t id) { fbb_.AddElement<int32_t>(FileWriteRequest::VT_ID, id, 0); }
  void add_data(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> data) { fbb_.AddOffset(FileWriteRequest::VT_DATA, data); }
  FileWriteRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  FileWriteRequestBuilder &operator=(const FileWriteRequestBuilder &);
  flatbuffers::Offset<FileWriteRequest> Finish() {
    auto o = flatbuffers::Offset<FileWriteRequest>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<FileWriteRequest> CreateFileWriteRequest(flatbuffers::FlatBufferBuilder &_fbb,
   int32_t id = 0,
   flatbuffers::Offset<flatbuffers::Vector<uint8_t>> data = 0) {
  FileWriteRequestBuilder builder_(_fbb);
  builder_.add_data(data);
  builder_.add_id(id);
  return builder_.Finish();
}

struct FileWriteResponse FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_SUCCESS = 4,
    VT_ERROR_MSG = 6,
    VT_BYTES_WRITTEN = 8
  };
  bool success() const { return GetField<uint8_t>(VT_SUCCESS, 0) != 0; }
  const flatbuffers::String *error_msg() const { return GetPointer<const flatbuffers::String *>(VT_ERROR_MSG); }
  uint64_t bytes_written() const { return GetField<uint64_t>(VT_BYTES_WRITTEN, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_SUCCESS) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_ERROR_MSG) &&
           verifier.Verify(error_msg()) &&
           VerifyField<uint64_t>(verifier, VT_BYTES_WRITTEN) &&
           verifier.EndTable();
  }
};

struct FileWriteResponseBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_success(bool success) { fbb_.AddElement<uint8_t>(FileWriteResponse::VT_SUCCESS, static_cast<uint8_t>(success), 0); }
  void add_error_msg(flatbuffers::Offset<flatbuffers::String> error_msg) { fbb_.AddOffset(FileWriteResponse::VT_ERROR_MSG, error_msg); }
  void add_bytes_written(uint64_t bytes_written) { fbb_.AddElement<uint64_t>(FileWriteResponse::VT_BYTES_WRITTEN, bytes_written, 0); }
  FileWriteResponseBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  FileWriteResponseBuilder &operator=(const FileWriteResponseBuilder &);
  flatbuffers::Offset<FileWriteResponse> Finish() {
    auto o = flatbuffers::Offset<FileWriteResponse>(fbb_.EndTable(start_, 3));
    return o;
  }
};

inline flatbuffers::Offset<FileWriteResponse> CreateFileWriteResponse(flatbuffers::FlatBufferBuilder &_fbb,
   bool success = false,
   flatbuffers::Offset<flatbuffers::String> error_msg = 0,
   uint64_t bytes_written = 0) {
  FileWriteResponseBuilder builder_(_fbb);
  builder_.add_bytes_written(bytes_written);
  builder_.add_error_msg(error_msg);
  builder_.add_success(success);
  return builder_.Finish();
}

}  // namespace v3
}  // namespace daemon
}  // namespace mbtool

#endif  // FLATBUFFERS_GENERATED_FILEWRITE_MBTOOL_DAEMON_V3_H_
