// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_FILEOPEN_MBTOOL_DAEMON_V3_H_
#define FLATBUFFERS_GENERATED_FILEOPEN_MBTOOL_DAEMON_V3_H_

#include "flatbuffers/flatbuffers.h"


namespace mbtool {
namespace daemon {
namespace v3 {

struct FileOpenRequest;
struct FileOpenResponse;

enum FileOpenFlag {
  FileOpenFlag_APPEND = 0,
  FileOpenFlag_CREAT = 1,
  FileOpenFlag_EXCL = 2,
  FileOpenFlag_RDONLY = 3,
  FileOpenFlag_RDWR = 4,
  FileOpenFlag_TRUNC = 5,
  FileOpenFlag_WRONLY = 6,
  FileOpenFlag_MIN = FileOpenFlag_APPEND,
  FileOpenFlag_MAX = FileOpenFlag_WRONLY
};

inline const char **EnumNamesFileOpenFlag() {
  static const char *names[] = { "APPEND", "CREAT", "EXCL", "RDONLY", "RDWR", "TRUNC", "WRONLY", nullptr };
  return names;
}

inline const char *EnumNameFileOpenFlag(FileOpenFlag e) { return EnumNamesFileOpenFlag()[static_cast<int>(e)]; }

struct FileOpenRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_PATH = 4,
    VT_FLAGS = 6,
    VT_PERMS = 8
  };
  const flatbuffers::String *path() const { return GetPointer<const flatbuffers::String *>(VT_PATH); }
  const flatbuffers::Vector<int16_t> *flags() const { return GetPointer<const flatbuffers::Vector<int16_t> *>(VT_FLAGS); }
  uint32_t perms() const { return GetField<uint32_t>(VT_PERMS, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_PATH) &&
           verifier.Verify(path()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_FLAGS) &&
           verifier.Verify(flags()) &&
           VerifyField<uint32_t>(verifier, VT_PERMS) &&
           verifier.EndTable();
  }
};

struct FileOpenRequestBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_path(flatbuffers::Offset<flatbuffers::String> path) { fbb_.AddOffset(FileOpenRequest::VT_PATH, path); }
  void add_flags(flatbuffers::Offset<flatbuffers::Vector<int16_t>> flags) { fbb_.AddOffset(FileOpenRequest::VT_FLAGS, flags); }
  void add_perms(uint32_t perms) { fbb_.AddElement<uint32_t>(FileOpenRequest::VT_PERMS, perms, 0); }
  FileOpenRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  FileOpenRequestBuilder &operator=(const FileOpenRequestBuilder &);
  flatbuffers::Offset<FileOpenRequest> Finish() {
    auto o = flatbuffers::Offset<FileOpenRequest>(fbb_.EndTable(start_, 3));
    return o;
  }
};

inline flatbuffers::Offset<FileOpenRequest> CreateFileOpenRequest(flatbuffers::FlatBufferBuilder &_fbb,
   flatbuffers::Offset<flatbuffers::String> path = 0,
   flatbuffers::Offset<flatbuffers::Vector<int16_t>> flags = 0,
   uint32_t perms = 0) {
  FileOpenRequestBuilder builder_(_fbb);
  builder_.add_perms(perms);
  builder_.add_flags(flags);
  builder_.add_path(path);
  return builder_.Finish();
}

struct FileOpenResponse FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_SUCCESS = 4,
    VT_ERROR_MSG = 6,
    VT_ID = 8
  };
  bool success() const { return GetField<uint8_t>(VT_SUCCESS, 0) != 0; }
  const flatbuffers::String *error_msg() const { return GetPointer<const flatbuffers::String *>(VT_ERROR_MSG); }
  int32_t id() const { return GetField<int32_t>(VT_ID, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_SUCCESS) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_ERROR_MSG) &&
           verifier.Verify(error_msg()) &&
           VerifyField<int32_t>(verifier, VT_ID) &&
           verifier.EndTable();
  }
};

struct FileOpenResponseBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_success(bool success) { fbb_.AddElement<uint8_t>(FileOpenResponse::VT_SUCCESS, static_cast<uint8_t>(success), 0); }
  void add_error_msg(flatbuffers::Offset<flatbuffers::String> error_msg) { fbb_.AddOffset(FileOpenResponse::VT_ERROR_MSG, error_msg); }
  void add_id(int32_t id) { fbb_.AddElement<int32_t>(FileOpenResponse::VT_ID, id, 0); }
  FileOpenResponseBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  FileOpenResponseBuilder &operator=(const FileOpenResponseBuilder &);
  flatbuffers::Offset<FileOpenResponse> Finish() {
    auto o = flatbuffers::Offset<FileOpenResponse>(fbb_.EndTable(start_, 3));
    return o;
  }
};

inline flatbuffers::Offset<FileOpenResponse> CreateFileOpenResponse(flatbuffers::FlatBufferBuilder &_fbb,
   bool success = false,
   flatbuffers::Offset<flatbuffers::String> error_msg = 0,
   int32_t id = 0) {
  FileOpenResponseBuilder builder_(_fbb);
  builder_.add_id(id);
  builder_.add_error_msg(error_msg);
  builder_.add_success(success);
  return builder_.Finish();
}

}  // namespace v3
}  // namespace daemon
}  // namespace mbtool

#endif  // FLATBUFFERS_GENERATED_FILEOPEN_MBTOOL_DAEMON_V3_H_
