// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_GETBUILTINROMIDS_MBTOOL_DAEMON_V2_H_
#define FLATBUFFERS_GENERATED_GETBUILTINROMIDS_MBTOOL_DAEMON_V2_H_

#include "flatbuffers/flatbuffers.h"

namespace mbtool {
namespace daemon {
namespace v2 {
struct GetVersionRequest;
struct GetVersionResponse;
}  // namespace v2
}  // namespace daemon
}  // namespace mbtool
namespace mbtool {
namespace daemon {
namespace v2 {
struct Rom;
struct GetRomsListRequest;
struct GetRomsListResponse;
}  // namespace v2
}  // namespace daemon
}  // namespace mbtool

namespace mbtool {
namespace daemon {
namespace v2 {

struct GetBuiltinRomIdsRequest;
struct GetBuiltinRomIdsResponse;

struct GetBuiltinRomIdsRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct GetBuiltinRomIdsRequestBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  GetBuiltinRomIdsRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  GetBuiltinRomIdsRequestBuilder &operator=(const GetBuiltinRomIdsRequestBuilder &);
  flatbuffers::Offset<GetBuiltinRomIdsRequest> Finish() {
    auto o = flatbuffers::Offset<GetBuiltinRomIdsRequest>(fbb_.EndTable(start_, 0));
    return o;
  }
};

inline flatbuffers::Offset<GetBuiltinRomIdsRequest> CreateGetBuiltinRomIdsRequest(flatbuffers::FlatBufferBuilder &_fbb) {
  GetBuiltinRomIdsRequestBuilder builder_(_fbb);
  return builder_.Finish();
}

struct GetBuiltinRomIdsResponse FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *rom_ids() const { return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *>(4); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 4 /* rom_ids */) &&
           verifier.Verify(rom_ids()) &&
           verifier.VerifyVectorOfStrings(rom_ids()) &&
           verifier.EndTable();
  }
};

struct GetBuiltinRomIdsResponseBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_rom_ids(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> rom_ids) { fbb_.AddOffset(4, rom_ids); }
  GetBuiltinRomIdsResponseBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  GetBuiltinRomIdsResponseBuilder &operator=(const GetBuiltinRomIdsResponseBuilder &);
  flatbuffers::Offset<GetBuiltinRomIdsResponse> Finish() {
    auto o = flatbuffers::Offset<GetBuiltinRomIdsResponse>(fbb_.EndTable(start_, 1));
    return o;
  }
};

inline flatbuffers::Offset<GetBuiltinRomIdsResponse> CreateGetBuiltinRomIdsResponse(flatbuffers::FlatBufferBuilder &_fbb,
   flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> rom_ids = 0) {
  GetBuiltinRomIdsResponseBuilder builder_(_fbb);
  builder_.add_rom_ids(rom_ids);
  return builder_.Finish();
}

}  // namespace v2
}  // namespace daemon
}  // namespace mbtool

#endif  // FLATBUFFERS_GENERATED_GETBUILTINROMIDS_MBTOOL_DAEMON_V2_H_
