// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PATHSELINUXGETLABEL_MBTOOL_DAEMON_V3_H_
#define FLATBUFFERS_GENERATED_PATHSELINUXGETLABEL_MBTOOL_DAEMON_V3_H_

#include "flatbuffers/flatbuffers.h"

namespace mbtool {
namespace daemon {
namespace v3 {

struct PathSELinuxGetLabelError;

struct PathSELinuxGetLabelRequest;

struct PathSELinuxGetLabelResponse;

struct PathSELinuxGetLabelError FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ERRNO_VALUE = 4,
    VT_MSG = 6
  };
  int32_t errno_value() const {
    return GetField<int32_t>(VT_ERRNO_VALUE, 0);
  }
  const flatbuffers::String *msg() const {
    return GetPointer<const flatbuffers::String *>(VT_MSG);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ERRNO_VALUE) &&
           VerifyOffset(verifier, VT_MSG) &&
           verifier.Verify(msg()) &&
           verifier.EndTable();
  }
};

struct PathSELinuxGetLabelErrorBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_errno_value(int32_t errno_value) {
    fbb_.AddElement<int32_t>(PathSELinuxGetLabelError::VT_ERRNO_VALUE, errno_value, 0);
  }
  void add_msg(flatbuffers::Offset<flatbuffers::String> msg) {
    fbb_.AddOffset(PathSELinuxGetLabelError::VT_MSG, msg);
  }
  explicit PathSELinuxGetLabelErrorBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  PathSELinuxGetLabelErrorBuilder &operator=(const PathSELinuxGetLabelErrorBuilder &);
  flatbuffers::Offset<PathSELinuxGetLabelError> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<PathSELinuxGetLabelError>(end);
    return o;
  }
};

inline flatbuffers::Offset<PathSELinuxGetLabelError> CreatePathSELinuxGetLabelError(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t errno_value = 0,
    flatbuffers::Offset<flatbuffers::String> msg = 0) {
  PathSELinuxGetLabelErrorBuilder builder_(_fbb);
  builder_.add_msg(msg);
  builder_.add_errno_value(errno_value);
  return builder_.Finish();
}

inline flatbuffers::Offset<PathSELinuxGetLabelError> CreatePathSELinuxGetLabelErrorDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t errno_value = 0,
    const char *msg = nullptr) {
  return mbtool::daemon::v3::CreatePathSELinuxGetLabelError(
      _fbb,
      errno_value,
      msg ? _fbb.CreateString(msg) : 0);
}

struct PathSELinuxGetLabelRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_PATH = 4,
    VT_FOLLOW_SYMLINKS = 6
  };
  const flatbuffers::String *path() const {
    return GetPointer<const flatbuffers::String *>(VT_PATH);
  }
  bool follow_symlinks() const {
    return GetField<uint8_t>(VT_FOLLOW_SYMLINKS, 0) != 0;
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PATH) &&
           verifier.Verify(path()) &&
           VerifyField<uint8_t>(verifier, VT_FOLLOW_SYMLINKS) &&
           verifier.EndTable();
  }
};

struct PathSELinuxGetLabelRequestBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_path(flatbuffers::Offset<flatbuffers::String> path) {
    fbb_.AddOffset(PathSELinuxGetLabelRequest::VT_PATH, path);
  }
  void add_follow_symlinks(bool follow_symlinks) {
    fbb_.AddElement<uint8_t>(PathSELinuxGetLabelRequest::VT_FOLLOW_SYMLINKS, static_cast<uint8_t>(follow_symlinks), 0);
  }
  explicit PathSELinuxGetLabelRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  PathSELinuxGetLabelRequestBuilder &operator=(const PathSELinuxGetLabelRequestBuilder &);
  flatbuffers::Offset<PathSELinuxGetLabelRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<PathSELinuxGetLabelRequest>(end);
    return o;
  }
};

inline flatbuffers::Offset<PathSELinuxGetLabelRequest> CreatePathSELinuxGetLabelRequest(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> path = 0,
    bool follow_symlinks = false) {
  PathSELinuxGetLabelRequestBuilder builder_(_fbb);
  builder_.add_path(path);
  builder_.add_follow_symlinks(follow_symlinks);
  return builder_.Finish();
}

inline flatbuffers::Offset<PathSELinuxGetLabelRequest> CreatePathSELinuxGetLabelRequestDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *path = nullptr,
    bool follow_symlinks = false) {
  return mbtool::daemon::v3::CreatePathSELinuxGetLabelRequest(
      _fbb,
      path ? _fbb.CreateString(path) : 0,
      follow_symlinks);
}

struct PathSELinuxGetLabelResponse FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_SUCCESS = 4,
    VT_ERROR_MSG = 6,
    VT_LABEL = 8,
    VT_ERROR = 10
  };
  bool success() const {
    return GetField<uint8_t>(VT_SUCCESS, 0) != 0;
  }
  const flatbuffers::String *error_msg() const {
    return GetPointer<const flatbuffers::String *>(VT_ERROR_MSG);
  }
  const flatbuffers::String *label() const {
    return GetPointer<const flatbuffers::String *>(VT_LABEL);
  }
  const PathSELinuxGetLabelError *error() const {
    return GetPointer<const PathSELinuxGetLabelError *>(VT_ERROR);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_SUCCESS) &&
           VerifyOffset(verifier, VT_ERROR_MSG) &&
           verifier.Verify(error_msg()) &&
           VerifyOffset(verifier, VT_LABEL) &&
           verifier.Verify(label()) &&
           VerifyOffset(verifier, VT_ERROR) &&
           verifier.VerifyTable(error()) &&
           verifier.EndTable();
  }
};

struct PathSELinuxGetLabelResponseBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_success(bool success) {
    fbb_.AddElement<uint8_t>(PathSELinuxGetLabelResponse::VT_SUCCESS, static_cast<uint8_t>(success), 0);
  }
  void add_error_msg(flatbuffers::Offset<flatbuffers::String> error_msg) {
    fbb_.AddOffset(PathSELinuxGetLabelResponse::VT_ERROR_MSG, error_msg);
  }
  void add_label(flatbuffers::Offset<flatbuffers::String> label) {
    fbb_.AddOffset(PathSELinuxGetLabelResponse::VT_LABEL, label);
  }
  void add_error(flatbuffers::Offset<PathSELinuxGetLabelError> error) {
    fbb_.AddOffset(PathSELinuxGetLabelResponse::VT_ERROR, error);
  }
  explicit PathSELinuxGetLabelResponseBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  PathSELinuxGetLabelResponseBuilder &operator=(const PathSELinuxGetLabelResponseBuilder &);
  flatbuffers::Offset<PathSELinuxGetLabelResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<PathSELinuxGetLabelResponse>(end);
    return o;
  }
};

inline flatbuffers::Offset<PathSELinuxGetLabelResponse> CreatePathSELinuxGetLabelResponse(
    flatbuffers::FlatBufferBuilder &_fbb,
    bool success = false,
    flatbuffers::Offset<flatbuffers::String> error_msg = 0,
    flatbuffers::Offset<flatbuffers::String> label = 0,
    flatbuffers::Offset<PathSELinuxGetLabelError> error = 0) {
  PathSELinuxGetLabelResponseBuilder builder_(_fbb);
  builder_.add_error(error);
  builder_.add_label(label);
  builder_.add_error_msg(error_msg);
  builder_.add_success(success);
  return builder_.Finish();
}

inline flatbuffers::Offset<PathSELinuxGetLabelResponse> CreatePathSELinuxGetLabelResponseDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    bool success = false,
    const char *error_msg = nullptr,
    const char *label = nullptr,
    flatbuffers::Offset<PathSELinuxGetLabelError> error = 0) {
  return mbtool::daemon::v3::CreatePathSELinuxGetLabelResponse(
      _fbb,
      success,
      error_msg ? _fbb.CreateString(error_msg) : 0,
      label ? _fbb.CreateString(label) : 0,
      error);
}

}  // namespace v3
}  // namespace daemon
}  // namespace mbtool

#endif  // FLATBUFFERS_GENERATED_PATHSELINUXGETLABEL_MBTOOL_DAEMON_V3_H_
