#!/sbin/busybox sh

if [ -f $2 ];then
	FILEVAR=$(basename $2)

	if [ -z $3 ]; then
		evalcmd='eval echo \$$FILEVAR'
		if [ "a`eval $evalcmd`" == "a" ]; then
			ON=`cat $2`
			if [ $ON -eq 0 ]; then
				VAL="off"
			else
				VAL="on"
			fi

			eval $FILEVAR=$VAL
			echo $FILEVAR=$VAL >> $DEFAULT_PROFILE
		fi
	else
		case "$3" in
			off)	echo 0 > $2	;;
			on)	echo 1 > $2	;;
		esac
		eval $FILEVAR=$3
	fi

	eval echo \$$FILEVAR
fi

