// automatically generated by the FlatBuffers compiler, do not modify

package mbtool.daemon.v3;

public final class FileOpenFlag {
  private FileOpenFlag() { }
  public static final short APPEND = 0;
  public static final short CREAT = 1;
  public static final short EXCL = 2;
  public static final short RDONLY = 3;
  public static final short RDWR = 4;
  public static final short TRUNC = 5;
  public static final short WRONLY = 6;

  public static final String[] names = { "APPEND", "CREAT", "EXCL", "RDONLY", "RDWR", "TRUNC", "WRONLY", };

  public static String name(int e) { return names[e]; }
}

