// automatically generated by the FlatBuffers compiler, do not modify

package mbtool.daemon.v3;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class MbSetKernelResponse extends Table {
  public static MbSetKernelResponse getRootAsMbSetKernelResponse(ByteBuffer _bb) { return getRootAsMbSetKernelResponse(_bb, new MbSetKernelResponse()); }
  public static MbSetKernelResponse getRootAsMbSetKernelResponse(ByteBuffer _bb, MbSetKernelResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public MbSetKernelResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean success() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public MbSetKernelError error() { return error(new MbSetKernelError()); }
  public MbSetKernelError error(MbSetKernelError obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createMbSetKernelResponse(FlatBufferBuilder builder,
      boolean success,
      int errorOffset) {
    builder.startObject(2);
    MbSetKernelResponse.addError(builder, errorOffset);
    MbSetKernelResponse.addSuccess(builder, success);
    return MbSetKernelResponse.endMbSetKernelResponse(builder);
  }

  public static void startMbSetKernelResponse(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addSuccess(FlatBufferBuilder builder, boolean success) { builder.addBoolean(0, success, false); }
  public static void addError(FlatBufferBuilder builder, int errorOffset) { builder.addOffset(1, errorOffset, 0); }
  public static int endMbSetKernelResponse(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

