// automatically generated by the FlatBuffers compiler, do not modify

package mbtool.daemon.v3;

public final class MbSwitchRomResult {
  private MbSwitchRomResult() { }
  public static final short SUCCEEDED = 0;
  public static final short FAILED = 1;
  public static final short CHECKSUM_NOT_FOUND = 2;
  public static final short CHECKSUM_INVALID = 3;

  public static final String[] names = { "SUCCEEDED", "FAILED", "CHECKSUM_NOT_FOUND", "CHECKSUM_INVALID", };

  public static String name(int e) { return names[e]; }
}

