// automatically generated by the FlatBuffers compiler, do not modify

package mbtool.daemon.v3;

public final class MbWipeTarget {
  private MbWipeTarget() { }
  public static final short SYSTEM = 0;
  public static final short CACHE = 1;
  public static final short DATA = 2;
  public static final short DALVIK_CACHE = 3;
  public static final short MULTIBOOT = 4;

  public static final String[] names = { "SYSTEM", "CACHE", "DATA", "DALVIK_CACHE", "MULTIBOOT", };

  public static String name(int e) { return names[e]; }
}

