// automatically generated by the FlatBuffers compiler, do not modify

package mbtool.daemon.v3;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class RebootError extends Table {
  public static RebootError getRootAsRebootError(ByteBuffer _bb) { return getRootAsRebootError(_bb, new RebootError()); }
  public static RebootError getRootAsRebootError(ByteBuffer _bb, RebootError obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public RebootError __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }


  public static void startRebootError(FlatBufferBuilder builder) { builder.startObject(0); }
  public static int endRebootError(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

