if(ANDROID)
    set(ANDROID_LIBCUTILS_INCLUDE_DIR
        ${THIRD_PARTY_ANDROID_SYSTEM_CORE_DIR}/${ANDROID_ABI}/include)
    set(ANDROID_LIBCUTILS_LIBRARY
        ${THIRD_PARTY_ANDROID_SYSTEM_CORE_DIR}/${ANDROID_ABI}/lib/libcutils.a)
    set(ANDROID_LIBLOG_INCLUDE_DIR
        ${THIRD_PARTY_ANDROID_SYSTEM_CORE_DIR}/${ANDROID_ABI}/include)
    set(ANDROID_LIBLOG_LIBRARY
        ${THIRD_PARTY_ANDROID_SYSTEM_CORE_DIR}/${ANDROID_ABI}/lib/liblog.a)
    set(ANDROID_LIBUTILS_INCLUDE_DIR
        ${THIRD_PARTY_ANDROID_SYSTEM_CORE_DIR}/${ANDROID_ABI}/include)
    set(ANDROID_LIBUTILS_LIBRARY
        ${THIRD_PARTY_ANDROID_SYSTEM_CORE_DIR}/${ANDROID_ABI}/lib/libutils.a)
    set(ANDROID_PIXELFLINGER_INCLUDE_DIR
        ${THIRD_PARTY_ANDROID_SYSTEM_CORE_DIR}/${ANDROID_ABI}/include)
    set(ANDROID_PIXELFLINGER_LIBRARY
        ${THIRD_PARTY_ANDROID_SYSTEM_CORE_DIR}/${ANDROID_ABI}/lib/libpixelflinger.a)
endif()

find_package(AndroidLibCutils REQUIRED)
find_package(AndroidLibLog REQUIRED)
find_package(AndroidLibUtils REQUIRED)
find_package(AndroidPixelFlinger REQUIRED)
