if(ANDROID)
    set(MBP_FREETYPE2_INCLUDES
        ${THIRD_PARTY_FREETYPE2_DIR}/${ANDROID_ABI}/include)
    set(MBP_FREETYPE2_LIBRARIES
        ${THIRD_PARTY_FREETYPE2_DIR}/${ANDROID_ABI}/lib/libft2.a)
endif()
