if(ANDROID)
    set(JANSSON_INCLUDE_DIR
        ${THIRD_PARTY_JANSSON_DIR}/${ANDROID_ABI}/include)
    set(JANSSON_LIBRARY
        ${THIRD_PARTY_JANSSON_DIR}/${ANDROID_ABI}/lib/libjansson.a)
endif()

find_package(Jansson REQUIRED)

set(MBP_JANSSON_INCLUDES ${JANSSON_INCLUDE_DIR})
set(MBP_JANSSON_LIBRARIES ${JANSSON_LIBRARIES})
