if(ANDROID)
    set(LIBLZMA_INCLUDE_DIR
        ${THIRD_PARTY_LIBLZMA_DIR}/${ANDROID_ABI}/include)
    set(LIBLZMA_LIBRARY
        ${THIRD_PARTY_LIBLZMA_DIR}/${ANDROID_ABI}/lib/liblzma.a)
endif()

find_package(LibLZMA REQUIRED)

set(MBP_LIBLZMA_INCLUDES ${LIBLZMA_INCLUDE_DIRS})
set(MBP_LIBLZMA_LIBRARIES ${LIBLZMA_LIBRARIES})
