if(ANDROID)
    set(MBP_LIBSEPOL_INCLUDES
        ${THIRD_PARTY_LIBSEPOL_DIR}/${ANDROID_ABI}/include)
    set(MBP_LIBSEPOL_LIBRARIES
        ${THIRD_PARTY_LIBSEPOL_DIR}/${ANDROID_ABI}/lib/libsepol.a)
endif()
