if(ANDROID)
    set(LZO_INCLUDE_DIR
        ${THIRD_PARTY_LZO_DIR}/${ANDROID_ABI}/include)
    set(LZO_LIBRARY
        ${THIRD_PARTY_LZO_DIR}/${ANDROID_ABI}/lib/liblzo2.a)
endif()

find_package(LZO REQUIRED)

set(MBP_LZO_INCLUDES ${LZO_INCLUDE_DIR})
set(MBP_LZO_LIBRARIES ${LZO_LIBRARIES})
