if(ANDROID)
    if(${MBP_BUILD_TARGET} STREQUAL android-system)
        set(CMAKE_FIND_LIBRARY_SUFFIXES_OLD ${CMAKE_FIND_LIBRARY_SUFFIXES})
        set(CMAKE_FIND_LIBRARY_SUFFIXES .a)
    endif()

    find_package(ZLIB)
    if(NOT ZLIB_FOUND)
        message(FATAL_ERROR "zlib is included with the Android NDK, but it was not found!")
    endif()

    set(MBP_ZLIB_INCLUDES ${ZLIB_INCLUDE_DIR})
    set(MBP_ZLIB_LIBRARIES ${ZLIB_LIBRARIES})

    if(${MBP_BUILD_TARGET} STREQUAL android-system)
        set(CMAKE_FIND_LIBRARY_SUFFIXES ${CMAKE_FIND_LIBRARY_SUFFIXES_OLD})
        unset(CMAKE_FIND_LIBRARY_SUFFIXES_OLD)
    endif()
else()
    find_package(ZLIB)
    if(NOT ZLIB_FOUND)
        message(FATAL_ERROR "MBP_USE_SYSTEM_ZLIB is ON but zlib is not found!")
    endif()

    set(MBP_ZLIB_INCLUDES ${ZLIB_INCLUDE_DIR})
    set(MBP_ZLIB_LIBRARIES ${ZLIB_LIBRARIES})
endif()
