#!/system/bin/sh
#Sound control camera mic gain
#Camera mic gain:
#60

echo "60" > /sys/kernel/sound_control/gpl_cam_mic_gain

# Display dialog window

if [ ! -f /system/etc/init.d/*dksouncammicgain_005-60 ]; then

	rm /sdcard/ausdim_twk_dlg_helper

	am start -a android.intent.action.MAIN -e message "Warning maybe you damage your phone mic." -e title "Sound control camera mic gain warning" -e okstyle "Ok" -n dk.ausdim.tweaks.dialog.helper/.AusdimTweaksDialogActivity

	while [ ! -f /sdcard/ausdim_twk_dlg_helper ]
	do
		/sbin/busybox sleep 1
	done

	rm /sdcard/ausdim_twk_dlg_helper

fi
