#!/system/bin/sh
#Wipe caches and reboot
#Wipes cache, Dalvik cache and reboot

TITLE="Wipe caches and reboot"
STYLE="Ok"

rm /sdcard/ausdim_twk_dlg_helper

am start -a android.intent.action.MAIN -e message "Do you really want to wipe cache, Dalvik cache and reboot?" -e title "$TITLE" -e button1 "Yes" -e button2 "No" -e toasty "Wipe caches and reboot now!" -e toastn "Wipe caches and reboot aborted!" -n dk.ausdim.tweaks.dialog.helper/.AusdimTweaksDialogActivity

while [ ! -f /sdcard/ausdim_twk_dlg_helper ]
do
  /sbin/busybox sleep 1
done

RESULT=`cat /sdcard/ausdim_twk_dlg_helper`

rm /sdcard/ausdim_twk_dlg_helper

if [ "$RESULT" = "yes" ]; then

	/sbin/busybox rm -rf /cache/*
	/sbin/busybox rm -rf /data/dalvik-cache/*
	/sbin/busybox sync
	/sbin/busybox sleep 2s
	/system/bin/reboot

fi
