#!/system/bin/sh
#Config: Delete ausdim-kernel.conf
#Deletes the ausdim-kernel.conf file (next start will create new standard config file)

TITLE="Config: Delete ausdim-kernel.conf"
STYLE="Ok"

if [ -f /sdcard/ausdim_twk_dlg_helper ]; then
  rm /sdcard/ausdim_twk_dlg_helper
fi;

am start -a android.intent.action.MAIN -e message "Do you really want to delete ausdim-kernel.conf?" -e title "$TITLE" -e button1 "Yes" -e button2 "No" -e toasty "Deleting ausdim-kernel.conf now!" -e toastn "Delete of ausdim-kernel.conf aborted!" -n dk.ausdim.tweaks.dialog.helper/.AusdimTweaksDialogActivity

while [ ! -f /sdcard/ausdim_twk_dlg_helper ]
do
  /sbin/busybox sleep 1
done

RESULT=`cat /sdcard/ausdim_twk_dlg_helper`

if [ "$RESULT" = "yes" ]; then

  if [ -f /sdcard/ausdim_twk_dlg_helper ]; then
    rm /sdcard/ausdim_twk_dlg_helper
  fi;

  /sbin/busybox rm /data/media/0/ausdim-kernel/ausdim-kernel.conf

am start -a android.intent.action.MAIN -e message "Delete ausdim-kernel.conf file done! Next start will create new standard config file." -e title "$TITLE" -e okstyle "$STYLE" -n dk.ausdim.tweaks.dialog.helper/.AusdimTweaksDialogActivity

else
  if [ -f /sdcard/ausdim_twk_dlg_helper ]; then
    rm /sdcard/ausdim_twk_dlg_helper
  fi;
  exit 0
fi;
