#!/system/bin/sh
#Config: Create ausdim-kernel folder
#Creates an empty ausdim-kernel folder on your sdcard

TITLE="Config: Create ausdim-kernel folder"
STYLE="Ok"

if [ -f /sdcard/ausdim_twk_dlg_helper ]; then
  rm /sdcard/ausdim_twk_dlg_helper
fi;

am start -a android.intent.action.MAIN -e message "Do you really want to create a ausdim-kernel folder?" -e title "$TITLE" -e button1 "Yes" -e button2 "No" -e toasty "Create ausdim-kernel folder now!" -e toastn "Create of ausdim-kernel folder aborted!" -n dk.ausdim.tweaks.dialog.helper/.AusdimTweaksDialogActivity

while [ ! -f /sdcard/ausdim_twk_dlg_helper ]
do
  /sbin/busybox sleep 1
done

RESULT=`cat /sdcard/ausdim_twk_dlg_helper`

if [ "$RESULT" = "yes" ]; then

  if [ -f /sdcard/ausdim_twk_dlg_helper ]; then
    rm /sdcard/ausdim_twk_dlg_helper
  fi;

  /sbin/busybox mkdir /sdcard/ausdim-kernel

am start -a android.intent.action.MAIN -e message "ausdim-kernel folder created! Now restart to get a fresh configuration file." -e title "$TITLE" -e okstyle "$STYLE" -n dk.ausdim.tweaks.dialog.helper/.AusdimTweaksDialogActivity

else
  if [ -f /sdcard/ausdim_twk_dlg_helper ]; then
    rm /sdcard/ausdim_twk_dlg_helper
  fi;
  exit 0
fi;
