#!/system/bin/sh
#Copy last_kmsg log file
#Run script to copy last_kmsg kernel log file to ausdim-kernel-data folder.

TITLE="Last_kmsg log"
STYLE="Ok"

LAST_KMSG_LOGFILE="/sdcard/ausdim-kernel-data/last_kmsg_log-$(date +%d.%m.%Y-%H.%M.%S-GMT).txt"

	cp /proc/last_kmsg $LAST_KMSG_LOGFILE

	am start -a android.intent.action.MAIN -e message "Logfile $LAST_KMSG_LOGFILE copied at sdcard/ausdim-kernel-data folder." -e title "$TITLE" -e okstyle "$STYLE" -n dk.ausdim.tweaks.dialog.helper/.AusdimTweaksDialogActivity
