#!/system/bin/sh
#App: Reset all settings
#Resets all settings done via the Ausdim Tweaks app

TITLE="App: Reset all settings"
STYLE="Ok"

if [ -f /sdcard/ausdim_twk_dlg_helper ]; then
  rm /sdcard/ausdim_twk_dlg_helper
fi;

am start -a android.intent.action.MAIN -e message "Do you really want to reset all Settings done via Ausdim Tweaks app?" -e title "$TITLE" -e button1 "Yes" -e button2 "No" -e toasty "Resetting Ausdim Tweaks settings now!" -e toastn "Reset of Ausdim Tweaks settings aborted!" -n dk.ausdim.tweaks.dialog.helper/.AusdimTweaksDialogActivity

while [ ! -f /sdcard/ausdim_twk_dlg_helper ]
do
  /sbin/busybox sleep 1
done


RESULT=`cat /sdcard/ausdim_twk_dlg_helper`

if [ "$RESULT" = "yes" ]; then

  if [ -f /sdcard/ausdim_twk_dlg_helper ]; then
    rm /sdcard/ausdim_twk_dlg_helper
  fi;

  SYSTEM_DEVICE="/dev/block/mmcblk0p16"

  /sbin/busybox mount -o remount,rw -t ext4 $SYSTEM_DEVICE /system
  /sbin/busybox rm /system/etc/init.d/*_dk*
  /sbin/busybox rm /system/etc/init.d/*_???dk*
  /sbin/busybox mount -o remount,ro -t ext4 $SYSTEM_DEVICE /system

am start -a android.intent.action.MAIN -e message "Reset of Ausdim Tweaks settings done! Changes will take effect after reboot!" -e title "$TITLE" -e okstyle "$STYLE" -n dk.ausdim.tweaks.dialog.helper/.AusdimTweaksDialogActivity

else
  if [ -f /sdcard/ausdim_twk_dlg_helper ]; then
    rm /sdcard/ausdim_twk_dlg_helper
  fi;
  exit 0
fi;
