#ifndef LIBDBPAUTOPATCHERCHENXIAOLONG_GLOBAL_H
#define LIBDBPAUTOPATCHERCHENXIAOLONG_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBDBPAUTOPATCHERCHENXIAOLONG_LIBRARY)
#  define LIBDBPAUTOPATCHERCHENXIAOLONGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBDBPAUTOPATCHERCHENXIAOLONGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBDBPAUTOPATCHERCHENXIAOLONG_GLOBAL_H
