#!/system/bin/sh
#init.d: Clean completely (ATTENTION)
#Remove all scripts from init.d folder and backup to sd card before - Note: This also applies to scripts placed there by your rom!!!

TITLE="init.d: Clean completely"
STYLE="Ok"

BACKUPFILE="/sdcard/ausdim-kernel-data/ausdim-initd-backup-$(date +"%d-%m-%Y %H:%M:%S-GMT").tar.gz"


if [ -f /sdcard/ausdim_twk_dlg_helper ]; then
  rm /sdcard/ausdim_twk_dlg_helper
fi;

am start -a android.intent.action.MAIN -e message "Do you really want to remove and backup ALL scripts from init.d folder?" -e title "$TITLE" -e button1 "Yes" -e button2 "No" -e toasty "Clean init.d folder now!" -e toastn "Clean init.d folder aborted!" -n dk.ausdim.tweaks.dialog.helper/.AusdimTweaksDialogActivity

while [ ! -f /sdcard/ausdim_twk_dlg_helper ]
do
  /sbin/busybox sleep 1
done

RESULT=`cat /sdcard/ausdim_twk_dlg_helper`

if [ "$RESULT" = "yes" ]; then

  if [ -f /sdcard/ausdim_twk_dlg_helper ]; then
    rm /sdcard/ausdim_twk_dlg_helper
  fi;

  /sbin/busybox tar cvz -f $BACKUPFILE /system/etc/init.d

  SYSTEM_DEVICE="/dev/block/mmcblk0p16"

  /sbin/busybox mount -o remount,rw -t ext4 $SYSTEM_DEVICE /system
  /sbin/busybox rm /system/etc/init.d/*
  /sbin/busybox mount -o remount,ro -t ext4 $SYSTEM_DEVICE /system

am start -a android.intent.action.MAIN -e message "Clean init.d folder done, backup created!" -e title "$TITLE" -e okstyle "$STYLE" -n dk.ausdim.tweaks.dialog.helper/.AusdimTweaksDialogActivity

else
  if [ -f /sdcard/ausdim_twk_dlg_helper ]; then
    rm /sdcard/ausdim_twk_dlg_helper
  fi;
  exit 0
fi;
