// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PATHMKDIR_MBTOOL_DAEMON_V3_H_
#define FLATBUFFERS_GENERATED_PATHMKDIR_MBTOOL_DAEMON_V3_H_

#include "flatbuffers/flatbuffers.h"

namespace mbtool {
namespace daemon {
namespace v3 {

struct PathMkdirError;

struct PathMkdirRequest;

struct PathMkdirResponse;

struct PathMkdirError FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ERRNO_VALUE = 4,
    VT_MSG = 6
  };
  int32_t errno_value() const {
    return GetField<int32_t>(VT_ERRNO_VALUE, 0);
  }
  const flatbuffers::String *msg() const {
    return GetPointer<const flatbuffers::String *>(VT_MSG);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ERRNO_VALUE) &&
           VerifyOffset(verifier, VT_MSG) &&
           verifier.Verify(msg()) &&
           verifier.EndTable();
  }
};

struct PathMkdirErrorBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_errno_value(int32_t errno_value) {
    fbb_.AddElement<int32_t>(PathMkdirError::VT_ERRNO_VALUE, errno_value, 0);
  }
  void add_msg(flatbuffers::Offset<flatbuffers::String> msg) {
    fbb_.AddOffset(PathMkdirError::VT_MSG, msg);
  }
  explicit PathMkdirErrorBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  PathMkdirErrorBuilder &operator=(const PathMkdirErrorBuilder &);
  flatbuffers::Offset<PathMkdirError> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<PathMkdirError>(end);
    return o;
  }
};

inline flatbuffers::Offset<PathMkdirError> CreatePathMkdirError(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t errno_value = 0,
    flatbuffers::Offset<flatbuffers::String> msg = 0) {
  PathMkdirErrorBuilder builder_(_fbb);
  builder_.add_msg(msg);
  builder_.add_errno_value(errno_value);
  return builder_.Finish();
}

inline flatbuffers::Offset<PathMkdirError> CreatePathMkdirErrorDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t errno_value = 0,
    const char *msg = nullptr) {
  return mbtool::daemon::v3::CreatePathMkdirError(
      _fbb,
      errno_value,
      msg ? _fbb.CreateString(msg) : 0);
}

struct PathMkdirRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_PATH = 4,
    VT_MODE = 6,
    VT_RECURSIVE = 8
  };
  const flatbuffers::String *path() const {
    return GetPointer<const flatbuffers::String *>(VT_PATH);
  }
  uint32_t mode() const {
    return GetField<uint32_t>(VT_MODE, 0);
  }
  bool recursive() const {
    return GetField<uint8_t>(VT_RECURSIVE, 0) != 0;
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PATH) &&
           verifier.Verify(path()) &&
           VerifyField<uint32_t>(verifier, VT_MODE) &&
           VerifyField<uint8_t>(verifier, VT_RECURSIVE) &&
           verifier.EndTable();
  }
};

struct PathMkdirRequestBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_path(flatbuffers::Offset<flatbuffers::String> path) {
    fbb_.AddOffset(PathMkdirRequest::VT_PATH, path);
  }
  void add_mode(uint32_t mode) {
    fbb_.AddElement<uint32_t>(PathMkdirRequest::VT_MODE, mode, 0);
  }
  void add_recursive(bool recursive) {
    fbb_.AddElement<uint8_t>(PathMkdirRequest::VT_RECURSIVE, static_cast<uint8_t>(recursive), 0);
  }
  explicit PathMkdirRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  PathMkdirRequestBuilder &operator=(const PathMkdirRequestBuilder &);
  flatbuffers::Offset<PathMkdirRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<PathMkdirRequest>(end);
    return o;
  }
};

inline flatbuffers::Offset<PathMkdirRequest> CreatePathMkdirRequest(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> path = 0,
    uint32_t mode = 0,
    bool recursive = false) {
  PathMkdirRequestBuilder builder_(_fbb);
  builder_.add_mode(mode);
  builder_.add_path(path);
  builder_.add_recursive(recursive);
  return builder_.Finish();
}

inline flatbuffers::Offset<PathMkdirRequest> CreatePathMkdirRequestDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *path = nullptr,
    uint32_t mode = 0,
    bool recursive = false) {
  return mbtool::daemon::v3::CreatePathMkdirRequest(
      _fbb,
      path ? _fbb.CreateString(path) : 0,
      mode,
      recursive);
}

struct PathMkdirResponse FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_SUCCESS = 4,
    VT_ERROR_MSG = 6,
    VT_ERROR = 8
  };
  bool success() const {
    return GetField<uint8_t>(VT_SUCCESS, 0) != 0;
  }
  const flatbuffers::String *error_msg() const {
    return GetPointer<const flatbuffers::String *>(VT_ERROR_MSG);
  }
  const PathMkdirError *error() const {
    return GetPointer<const PathMkdirError *>(VT_ERROR);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_SUCCESS) &&
           VerifyOffset(verifier, VT_ERROR_MSG) &&
           verifier.Verify(error_msg()) &&
           VerifyOffset(verifier, VT_ERROR) &&
           verifier.VerifyTable(error()) &&
           verifier.EndTable();
  }
};

struct PathMkdirResponseBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_success(bool success) {
    fbb_.AddElement<uint8_t>(PathMkdirResponse::VT_SUCCESS, static_cast<uint8_t>(success), 0);
  }
  void add_error_msg(flatbuffers::Offset<flatbuffers::String> error_msg) {
    fbb_.AddOffset(PathMkdirResponse::VT_ERROR_MSG, error_msg);
  }
  void add_error(flatbuffers::Offset<PathMkdirError> error) {
    fbb_.AddOffset(PathMkdirResponse::VT_ERROR, error);
  }
  explicit PathMkdirResponseBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  PathMkdirResponseBuilder &operator=(const PathMkdirResponseBuilder &);
  flatbuffers::Offset<PathMkdirResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<PathMkdirResponse>(end);
    return o;
  }
};

inline flatbuffers::Offset<PathMkdirResponse> CreatePathMkdirResponse(
    flatbuffers::FlatBufferBuilder &_fbb,
    bool success = false,
    flatbuffers::Offset<flatbuffers::String> error_msg = 0,
    flatbuffers::Offset<PathMkdirError> error = 0) {
  PathMkdirResponseBuilder builder_(_fbb);
  builder_.add_error(error);
  builder_.add_error_msg(error_msg);
  builder_.add_success(success);
  return builder_.Finish();
}

inline flatbuffers::Offset<PathMkdirResponse> CreatePathMkdirResponseDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    bool success = false,
    const char *error_msg = nullptr,
    flatbuffers::Offset<PathMkdirError> error = 0) {
  return mbtool::daemon::v3::CreatePathMkdirResponse(
      _fbb,
      success,
      error_msg ? _fbb.CreateString(error_msg) : 0,
      error);
}

}  // namespace v3
}  // namespace daemon
}  // namespace mbtool

#endif  // FLATBUFFERS_GENERATED_PATHMKDIR_MBTOOL_DAEMON_V3_H_
