// automatically generated by the FlatBuffers compiler, do not modify

package mbtool.daemon.v3;

public final class CryptoPwType {
  private CryptoPwType() { }
  public static final short DEFAULT = 0;
  public static final short PASSWORD = 1;
  public static final short PATTERN = 2;
  public static final short PIN = 3;
  public static final short UNKNOWN = 4;

  public static final String[] names = { "DEFAULT", "PASSWORD", "PATTERN", "PIN", "UNKNOWN", };

  public static String name(int e) { return names[e]; }
}

