// automatically generated by the FlatBuffers compiler, do not modify

package mbtool.daemon.v3;

public final class FileSeekWhence {
  private FileSeekWhence() { }
  public static final short SEEK_SET = 0;
  public static final short SEEK_CUR = 1;
  public static final short SEEK_END = 2;

  public static final String[] names = { "SEEK_SET", "SEEK_CUR", "SEEK_END", };

  public static String name(int e) { return names[e]; }
}

