#!/system/bin/sh
#Sound control speaker gain
#Speaker gain:
#60

echo "60" > /sys/kernel/sound_control/gpl_speaker_gain

# Display dialog window

if [ ! -f /system/etc/init.d/*dksoundspkgain_004-60 ]; then

	rm /sdcard/ausdim_twk_dlg_helper

	am start -a android.intent.action.MAIN -e message "Warning maybe you damage your speaker." -e title "Sound control speaker gain warning" -e okstyle "Ok" -n dk.ausdim.tweaks.dialog.helper/.AusdimTweaksDialogActivity

	while [ ! -f /sdcard/ausdim_twk_dlg_helper ]
	do
		/sbin/busybox sleep 1
	done

	rm /sdcard/ausdim_twk_dlg_helper

fi
