#ifndef LIBDBPRAMDISKCOMMON_GLOBAL_H
#define LIBDBPRAMDISKCOMMON_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBDBPRAMDISKCOMMON_LIBRARY)
#  define LIBDBPRAMDISKCOMMONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBDBPRAMDISKCOMMONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBDBPRAMDISKCOMMON_GLOBAL_H
