# Copyright (C) 2017  Andrew Gunnerson <andrewgunnerson@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

FROM @REPO@:@VERSION@-@RELEASE@-base

# Install dependencies
RUN dnf -y install dnf-plugins-core \
    && dnf -y copr enable chenxiaolong/mingw \
    && dnf -y install \
        mingw32-gtest \
        mingw32-libarchive \
        mingw32-jansson \
        mingw32-qt5-qtbase \
        upx \
        wine \
    && dnf clean all
