#!/sbin/busybox sh

SWITCH=CONTROLSWITCH_`echo $2`

if [ -z $3 ]; then
	evalcmd='eval echo \$$SWITCH'
	if [ "a`eval $evalcmd`" == "a" ]; then
		eval $SWITCH=off
		echo $SWITCH=off >> $DEFAULT_PROFILE
	fi
else
	case "$3" in
		off)	eval $SWITCH=off	;;
		on)	eval $SWITCH=on		;;
	esac
fi

eval echo \$$SWITCH

