#!/sbin/busybox sh

FILEVAR=$2_iosched

if [ -z $4 ]; then
	evalcmd='eval echo \$$FILEVAR'
	if [ "a`eval $evalcmd`" == "a" ]; then
		sleep 2
		VAL=`cat $3 | sed -n -e '/\[[^]]/s/^[^[]*\[\([^]]*\)].*$/\1/p'`
		eval $FILEVAR=$VAL
		echo $FILEVAR=$VAL >> $DEFAULT_PROFILE
	fi
else
	if [ -f $3 ];then
		echo $4 > $3
		eval $FILEVAR=`cat $3 | sed -n -e '/\[[^]]/s/^[^[]*\[\([^]]*\)].*$/\1/p'`
	else
		eval $FILEVAR=$4
	fi
fi

eval echo \$$FILEVAR
